name: Maven Test
on: [push]
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Package plugin
        run: mvn clean package -DskipTests=true
      - name: Run tests
        run: mvn -B test